YEAR=2015
DAY=19
include ../../make_vars.inc
OBJECTS = \
	$(LIB)/arrays.o \

all: $(BIN)/medicine_for_rudolph input.txt
	$(BIN)/medicine_for_rudolph < input.txt

ex1: $(BIN)/medicine_for_rudolph
	$(BIN)/medicine_for_rudolph < example_1.txt

ex2: $(BIN)/medicine_for_rudolph
	$(BIN)/medicine_for_rudolph < example_2.txt

include ../../makefile.inc
