include ../../makefile.inc

all: $(BIN)/medicine_for_rudolph
	aocd 2015 19 | $(BIN)/medicine_for_rudolph

ex1: $(BIN)/medicine_for_rudolph
	cat example_1.txt | $(BIN)/medicine_for_rudolph

ex2: $(BIN)/medicine_for_rudolph
	cat example_2.txt | $(BIN)/medicine_for_rudolph
