include ../make_vars.inc

$(OUT)/get_opts.s: \
		$(OUT)/allocator.jstd.jnh \
		$(OUT)/HashMap.jstd.jnh \
		$(OUT)/string.jstd.jnh \
		get_opts.jn
	${CATPILE}

$(OUT)/Graph.s: \
		$(OUT)/allocator.jstd.jnh \
		$(OUT)/ArrayList.jstd.jnh \
		$(OUT)/HashMap.jstd.jnh \
		Graph.jn
	${CATPILE}

include ../makefile.inc
